/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertStatus = { 'Active' : null } |
  { 'Dismissed' : null };
export interface BudgetStatus {
  'spent' : number,
  'remaining' : number,
  'budget' : number,
  'percentage' : number,
}
export interface ChatEntry {
  'id' : bigint,
  'content' : string,
  'role' : string,
  'callerId' : Principal,
  'timestamp' : bigint,
}
export interface ChatEntryInput { 'content' : string, 'role' : string }
export interface ChatRequest { 'context' : string, 'message' : string }
export interface ChatResponse { 'response' : string, 'timestamp' : bigint }
export interface DocumentMeta {
  'id' : bigint,
  'name' : string,
  'size' : bigint,
  'fileType' : string,
  'callerId' : Principal,
  'uploadedAt' : bigint,
}
export interface DocumentMetaInput {
  'name' : string,
  'size' : bigint,
  'fileType' : string,
}
export interface Expense {
  'id' : bigint,
  'paymentMethod' : PaymentMethod,
  'source' : string,
  'date' : string,
  'note' : string,
  'createdAt' : bigint,
  'callerId' : Principal,
  'updatedAt' : [] | [bigint],
  'merchant' : string,
  'category' : ExpenseCategory,
  'amount' : number,
}
export type ExpenseCategory = { 'Food' : null } |
  { 'Health' : null } |
  { 'Bills' : null } |
  { 'Travel' : null } |
  { 'Entertainment' : null } |
  { 'Shopping' : null } |
  { 'Other' : null } |
  { 'Transport' : null };
export interface ExpenseInput {
  'paymentMethod' : PaymentMethod,
  'source' : string,
  'date' : string,
  'note' : string,
  'merchant' : string,
  'category' : ExpenseCategory,
  'amount' : number,
}
export interface ExpenseSummary {
  'avgExpense' : number,
  'total' : number,
  'count' : bigint,
  'thisMonthTotal' : number,
  'thisMonthCount' : bigint,
  'topCategory' : string,
}
export interface ExpenseUpdateInput {
  'paymentMethod' : [] | [PaymentMethod],
  'date' : [] | [string],
  'note' : [] | [string],
  'merchant' : [] | [string],
  'category' : [] | [ExpenseCategory],
  'amount' : [] | [number],
}
export type PaymentMethod = { 'UPI' : null } |
  { 'Card' : null } |
  { 'Cash' : null } |
  { 'Other' : null } |
  { 'NetBanking' : null };
export type RiskLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface SpendingAlert {
  'status' : AlertStatus,
  'threshold' : number,
  'spent' : number,
  'category' : string,
}
export interface SpendingMonitorSettingsView {
  'monitoredCategories' : Array<string>,
  'consentGiven' : boolean,
  'thresholds' : Array<[string, number]>,
}
export interface ThemeOption {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface ThemePreference {
  'mode' : string,
  'palette' : string,
  'customColor' : [] | [string],
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'monthlyBudget' : number,
  'name' : string,
  'email' : string,
  'currency' : string,
}
export interface UserProfileInput {
  'monthlyBudget' : number,
  'name' : string,
  'email' : string,
  'currency' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addChatMessage' : ActorMethod<[ChatEntryInput], undefined>,
  'addExpense' : ActorMethod<[ExpenseInput], Expense>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chatAssistant' : ActorMethod<[ChatRequest], ChatResponse>,
  'checkCategorySpending' : ActorMethod<[], Array<SpendingAlert>>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'deleteDocument' : ActorMethod<[bigint], boolean>,
  'deleteExpense' : ActorMethod<[bigint], boolean>,
  'generateInsights' : ActorMethod<[], Array<string>>,
  'getAIResponse' : ActorMethod<[string, string], string>,
  'getAllThemeOptions' : ActorMethod<[], Array<ThemeOption>>,
  'getBudgetStatus' : ActorMethod<[], BudgetStatus>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryStats' : ActorMethod<[], Array<[string, number]>>,
  'getChatHistory' : ActorMethod<[], Array<ChatEntry>>,
  'getDocumentMeta' : ActorMethod<[bigint], [] | [DocumentMeta]>,
  'getExpenseSummary' : ActorMethod<[], ExpenseSummary>,
  'getRiskLevel' : ActorMethod<[], RiskLevel>,
  'getSpendingAlerts' : ActorMethod<[], Array<SpendingAlert>>,
  'getSpendingMonitorSettings' : ActorMethod<[], SpendingMonitorSettingsView>,
  'getSpendingPersonality' : ActorMethod<[], string>,
  'getUserTheme' : ActorMethod<[], [] | [ThemePreference]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDocuments' : ActorMethod<[], Array<DocumentMeta>>,
  'listExpenses' : ActorMethod<[], Array<Expense>>,
  'registerSpendingMonitorConsent' : ActorMethod<[boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'saveUserTheme' : ActorMethod<[ThemePreference], undefined>,
  'setAnthropicApiKey' : ActorMethod<[string], undefined>,
  'setCategoryThreshold' : ActorMethod<[string, number], undefined>,
  'setMonitoredCategories' : ActorMethod<[Array<string>], undefined>,
  'transformHttpResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'updateExpense' : ActorMethod<[bigint, ExpenseUpdateInput], boolean>,
  'uploadDocument' : ActorMethod<[DocumentMetaInput], DocumentMeta>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];