/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ChatEntryInput = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
  'Cash' : IDL.Null,
  'Other' : IDL.Null,
  'NetBanking' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'Food' : IDL.Null,
  'Health' : IDL.Null,
  'Bills' : IDL.Null,
  'Travel' : IDL.Null,
  'Entertainment' : IDL.Null,
  'Shopping' : IDL.Null,
  'Other' : IDL.Null,
  'Transport' : IDL.Null,
});
export const ExpenseInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'source' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'merchant' : IDL.Text,
  'category' : ExpenseCategory,
  'amount' : IDL.Float64,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'source' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'callerId' : IDL.Principal,
  'updatedAt' : IDL.Opt(IDL.Int),
  'merchant' : IDL.Text,
  'category' : ExpenseCategory,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatRequest = IDL.Record({
  'context' : IDL.Text,
  'message' : IDL.Text,
});
export const ChatResponse = IDL.Record({
  'response' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const AlertStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Dismissed' : IDL.Null,
});
export const SpendingAlert = IDL.Record({
  'status' : AlertStatus,
  'threshold' : IDL.Float64,
  'spent' : IDL.Float64,
  'category' : IDL.Text,
});
export const ThemeOption = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const BudgetStatus = IDL.Record({
  'spent' : IDL.Float64,
  'remaining' : IDL.Float64,
  'budget' : IDL.Float64,
  'percentage' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'monthlyBudget' : IDL.Float64,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'currency' : IDL.Text,
});
export const ChatEntry = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'callerId' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const DocumentMeta = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'fileType' : IDL.Text,
  'callerId' : IDL.Principal,
  'uploadedAt' : IDL.Int,
});
export const ExpenseSummary = IDL.Record({
  'avgExpense' : IDL.Float64,
  'total' : IDL.Float64,
  'count' : IDL.Nat,
  'thisMonthTotal' : IDL.Float64,
  'thisMonthCount' : IDL.Nat,
  'topCategory' : IDL.Text,
});
export const RiskLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const SpendingMonitorSettingsView = IDL.Record({
  'monitoredCategories' : IDL.Vec(IDL.Text),
  'consentGiven' : IDL.Bool,
  'thresholds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const ThemePreference = IDL.Record({
  'mode' : IDL.Text,
  'palette' : IDL.Text,
  'customColor' : IDL.Opt(IDL.Text),
});
export const UserProfileInput = IDL.Record({
  'monthlyBudget' : IDL.Float64,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'currency' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const ExpenseUpdateInput = IDL.Record({
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'date' : IDL.Opt(IDL.Text),
  'note' : IDL.Opt(IDL.Text),
  'merchant' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(ExpenseCategory),
  'amount' : IDL.Opt(IDL.Float64),
});
export const DocumentMetaInput = IDL.Record({
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'fileType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addChatMessage' : IDL.Func([ChatEntryInput], [], []),
  'addExpense' : IDL.Func([ExpenseInput], [Expense], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chatAssistant' : IDL.Func([ChatRequest], [ChatResponse], []),
  'checkCategorySpending' : IDL.Func([], [IDL.Vec(SpendingAlert)], ['query']),
  'clearChatHistory' : IDL.Func([], [], []),
  'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateInsights' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAIResponse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllThemeOptions' : IDL.Func([], [IDL.Vec(ThemeOption)], ['query']),
  'getBudgetStatus' : IDL.Func([], [BudgetStatus], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatEntry)], ['query']),
  'getDocumentMeta' : IDL.Func([IDL.Nat], [IDL.Opt(DocumentMeta)], ['query']),
  'getExpenseSummary' : IDL.Func([], [ExpenseSummary], ['query']),
  'getRiskLevel' : IDL.Func([], [RiskLevel], ['query']),
  'getSpendingAlerts' : IDL.Func([], [IDL.Vec(SpendingAlert)], ['query']),
  'getSpendingMonitorSettings' : IDL.Func(
      [],
      [SpendingMonitorSettingsView],
      ['query'],
    ),
  'getSpendingPersonality' : IDL.Func([], [IDL.Text], ['query']),
  'getUserTheme' : IDL.Func([], [IDL.Opt(ThemePreference)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDocuments' : IDL.Func([], [IDL.Vec(DocumentMeta)], ['query']),
  'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'registerSpendingMonitorConsent' : IDL.Func([IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'saveUserTheme' : IDL.Func([ThemePreference], [], []),
  'setAnthropicApiKey' : IDL.Func([IDL.Text], [], []),
  'setCategoryThreshold' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'setMonitoredCategories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'transformHttpResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateExpense' : IDL.Func([IDL.Nat, ExpenseUpdateInput], [IDL.Bool], []),
  'uploadDocument' : IDL.Func([DocumentMetaInput], [DocumentMeta], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ChatEntryInput = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
    'Cash' : IDL.Null,
    'Other' : IDL.Null,
    'NetBanking' : IDL.Null,
  });
  const ExpenseCategory = IDL.Variant({
    'Food' : IDL.Null,
    'Health' : IDL.Null,
    'Bills' : IDL.Null,
    'Travel' : IDL.Null,
    'Entertainment' : IDL.Null,
    'Shopping' : IDL.Null,
    'Other' : IDL.Null,
    'Transport' : IDL.Null,
  });
  const ExpenseInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'source' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'merchant' : IDL.Text,
    'category' : ExpenseCategory,
    'amount' : IDL.Float64,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'source' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'callerId' : IDL.Principal,
    'updatedAt' : IDL.Opt(IDL.Int),
    'merchant' : IDL.Text,
    'category' : ExpenseCategory,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatRequest = IDL.Record({
    'context' : IDL.Text,
    'message' : IDL.Text,
  });
  const ChatResponse = IDL.Record({
    'response' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const AlertStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Dismissed' : IDL.Null,
  });
  const SpendingAlert = IDL.Record({
    'status' : AlertStatus,
    'threshold' : IDL.Float64,
    'spent' : IDL.Float64,
    'category' : IDL.Text,
  });
  const ThemeOption = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const BudgetStatus = IDL.Record({
    'spent' : IDL.Float64,
    'remaining' : IDL.Float64,
    'budget' : IDL.Float64,
    'percentage' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'monthlyBudget' : IDL.Float64,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'currency' : IDL.Text,
  });
  const ChatEntry = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'callerId' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const DocumentMeta = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'fileType' : IDL.Text,
    'callerId' : IDL.Principal,
    'uploadedAt' : IDL.Int,
  });
  const ExpenseSummary = IDL.Record({
    'avgExpense' : IDL.Float64,
    'total' : IDL.Float64,
    'count' : IDL.Nat,
    'thisMonthTotal' : IDL.Float64,
    'thisMonthCount' : IDL.Nat,
    'topCategory' : IDL.Text,
  });
  const RiskLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const SpendingMonitorSettingsView = IDL.Record({
    'monitoredCategories' : IDL.Vec(IDL.Text),
    'consentGiven' : IDL.Bool,
    'thresholds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const ThemePreference = IDL.Record({
    'mode' : IDL.Text,
    'palette' : IDL.Text,
    'customColor' : IDL.Opt(IDL.Text),
  });
  const UserProfileInput = IDL.Record({
    'monthlyBudget' : IDL.Float64,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'currency' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const ExpenseUpdateInput = IDL.Record({
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'date' : IDL.Opt(IDL.Text),
    'note' : IDL.Opt(IDL.Text),
    'merchant' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(ExpenseCategory),
    'amount' : IDL.Opt(IDL.Float64),
  });
  const DocumentMetaInput = IDL.Record({
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'fileType' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addChatMessage' : IDL.Func([ChatEntryInput], [], []),
    'addExpense' : IDL.Func([ExpenseInput], [Expense], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chatAssistant' : IDL.Func([ChatRequest], [ChatResponse], []),
    'checkCategorySpending' : IDL.Func([], [IDL.Vec(SpendingAlert)], ['query']),
    'clearChatHistory' : IDL.Func([], [], []),
    'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateInsights' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAIResponse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAllThemeOptions' : IDL.Func([], [IDL.Vec(ThemeOption)], ['query']),
    'getBudgetStatus' : IDL.Func([], [BudgetStatus], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatEntry)], ['query']),
    'getDocumentMeta' : IDL.Func([IDL.Nat], [IDL.Opt(DocumentMeta)], ['query']),
    'getExpenseSummary' : IDL.Func([], [ExpenseSummary], ['query']),
    'getRiskLevel' : IDL.Func([], [RiskLevel], ['query']),
    'getSpendingAlerts' : IDL.Func([], [IDL.Vec(SpendingAlert)], ['query']),
    'getSpendingMonitorSettings' : IDL.Func(
        [],
        [SpendingMonitorSettingsView],
        ['query'],
      ),
    'getSpendingPersonality' : IDL.Func([], [IDL.Text], ['query']),
    'getUserTheme' : IDL.Func([], [IDL.Opt(ThemePreference)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDocuments' : IDL.Func([], [IDL.Vec(DocumentMeta)], ['query']),
    'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'registerSpendingMonitorConsent' : IDL.Func([IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'saveUserTheme' : IDL.Func([ThemePreference], [], []),
    'setAnthropicApiKey' : IDL.Func([IDL.Text], [], []),
    'setCategoryThreshold' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'setMonitoredCategories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'transformHttpResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateExpense' : IDL.Func([IDL.Nat, ExpenseUpdateInput], [IDL.Bool], []),
    'uploadDocument' : IDL.Func([DocumentMetaInput], [DocumentMeta], []),
  });
};

export const init = ({ IDL }) => { return []; };