/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface BudgetStatus {
    spent: number;
    remaining: number;
    budget: number;
    percentage: number;
}
export interface SpendingMonitorSettingsView {
    monitoredCategories: Array<string>;
    consentGiven: boolean;
    thresholds: Array<[string, number]>;
}
export interface ChatEntryInput {
    content: string;
    role: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface SpendingAlert {
    status: AlertStatus;
    threshold: number;
    spent: number;
    category: string;
}
export interface ChatRequest {
    context: string;
    message: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ExpenseInput {
    paymentMethod: PaymentMethod;
    source: string;
    date: string;
    note: string;
    merchant: string;
    category: ExpenseCategory;
    amount: number;
}
export interface ThemeOption {
    id: string;
    name: string;
    description: string;
}
export interface ChatEntry {
    id: bigint;
    content: string;
    role: string;
    callerId: Principal;
    timestamp: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ExpenseUpdateInput {
    paymentMethod?: PaymentMethod;
    date?: string;
    note?: string;
    merchant?: string;
    category?: ExpenseCategory;
    amount?: number;
}
export interface Expense {
    id: bigint;
    paymentMethod: PaymentMethod;
    source: string;
    date: string;
    note: string;
    createdAt: bigint;
    callerId: Principal;
    updatedAt?: bigint;
    merchant: string;
    category: ExpenseCategory;
    amount: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface DocumentMeta {
    id: bigint;
    name: string;
    size: bigint;
    fileType: string;
    callerId: Principal;
    uploadedAt: bigint;
}
export interface ThemePreference {
    mode: string;
    palette: string;
    customColor?: string;
}
export interface ChatResponse {
    response: string;
    timestamp: bigint;
}
export interface DocumentMetaInput {
    name: string;
    size: bigint;
    fileType: string;
}
export interface UserProfileInput {
    monthlyBudget: number;
    name: string;
    email: string;
    currency: string;
}
export interface UserProfile {
    monthlyBudget: number;
    name: string;
    email: string;
    currency: string;
}
export interface ExpenseSummary {
    avgExpense: number;
    total: number;
    count: bigint;
    thisMonthTotal: number;
    thisMonthCount: bigint;
    topCategory: string;
}
export enum AlertStatus {
    Active = "Active",
    Dismissed = "Dismissed"
}
export enum ExpenseCategory {
    Food = "Food",
    Health = "Health",
    Bills = "Bills",
    Travel = "Travel",
    Entertainment = "Entertainment",
    Shopping = "Shopping",
    Other = "Other",
    Transport = "Transport"
}
export enum PaymentMethod {
    UPI = "UPI",
    Card = "Card",
    Cash = "Cash",
    Other = "Other",
    NetBanking = "NetBanking"
}
export enum RiskLevel {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addChatMessage(input: ChatEntryInput): Promise<void>;
    addExpense(input: ExpenseInput): Promise<Expense>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    chatAssistant(request: ChatRequest): Promise<ChatResponse>;
    checkCategorySpending(): Promise<Array<SpendingAlert>>;
    clearChatHistory(): Promise<void>;
    deleteDocument(id: bigint): Promise<boolean>;
    deleteExpense(id: bigint): Promise<boolean>;
    generateInsights(): Promise<Array<string>>;
    getAIResponse(userMessage: string, expenseContext: string): Promise<string>;
    getAllThemeOptions(): Promise<Array<ThemeOption>>;
    getBudgetStatus(): Promise<BudgetStatus>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryStats(): Promise<Array<[string, number]>>;
    getChatHistory(): Promise<Array<ChatEntry>>;
    getDocumentMeta(id: bigint): Promise<DocumentMeta | null>;
    getExpenseSummary(): Promise<ExpenseSummary>;
    getRiskLevel(): Promise<RiskLevel>;
    getSpendingAlerts(): Promise<Array<SpendingAlert>>;
    getSpendingMonitorSettings(): Promise<SpendingMonitorSettingsView>;
    getSpendingPersonality(): Promise<string>;
    getUserTheme(): Promise<ThemePreference | null>;
    isCallerAdmin(): Promise<boolean>;
    listDocuments(): Promise<Array<DocumentMeta>>;
    listExpenses(): Promise<Array<Expense>>;
    registerSpendingMonitorConsent(consent: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfileInput): Promise<void>;
    saveUserTheme(theme: ThemePreference): Promise<void>;
    setAnthropicApiKey(key: string): Promise<void>;
    setCategoryThreshold(category: string, threshold: number): Promise<void>;
    setMonitoredCategories(categories: Array<string>): Promise<void>;
    transformHttpResponse(input: TransformationInput): Promise<TransformationOutput>;
    updateExpense(id: bigint, input: ExpenseUpdateInput): Promise<boolean>;
    uploadDocument(meta: DocumentMetaInput): Promise<DocumentMeta>;
}
import type { AlertStatus as _AlertStatus, DocumentMeta as _DocumentMeta, Expense as _Expense, ExpenseCategory as _ExpenseCategory, ExpenseInput as _ExpenseInput, ExpenseUpdateInput as _ExpenseUpdateInput, PaymentMethod as _PaymentMethod, RiskLevel as _RiskLevel, SpendingAlert as _SpendingAlert, ThemePreference as _ThemePreference, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addChatMessage(arg0: ChatEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChatMessage(arg0);
            return result;
        }
    }
    async addExpense(arg0: ExpenseInput): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_ExpenseInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Expense_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_ExpenseInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Expense_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async chatAssistant(arg0: ChatRequest): Promise<ChatResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.chatAssistant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chatAssistant(arg0);
            return result;
        }
    }
    async checkCategorySpending(): Promise<Array<SpendingAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.checkCategorySpending();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkCategorySpending();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearChatHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatHistory();
            return result;
        }
    }
    async deleteDocument(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async generateInsights(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInsights();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInsights();
            return result;
        }
    }
    async getAIResponse(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIResponse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIResponse(arg0, arg1);
            return result;
        }
    }
    async getAllThemeOptions(): Promise<Array<ThemeOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllThemeOptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllThemeOptions();
            return result;
        }
    }
    async getBudgetStatus(): Promise<BudgetStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetStatus();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryStats(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryStats();
            return result;
        }
    }
    async getChatHistory(): Promise<Array<ChatEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return result;
        }
    }
    async getDocumentMeta(arg0: bigint): Promise<DocumentMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentMeta(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentMeta(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseSummary(): Promise<ExpenseSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseSummary();
            return result;
        }
    }
    async getRiskLevel(): Promise<RiskLevel> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskLevel();
                return from_candid_RiskLevel_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskLevel();
            return from_candid_RiskLevel_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpendingAlerts(): Promise<Array<SpendingAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpendingAlerts();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpendingAlerts();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpendingMonitorSettings(): Promise<SpendingMonitorSettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpendingMonitorSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpendingMonitorSettings();
            return result;
        }
    }
    async getSpendingPersonality(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpendingPersonality();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpendingPersonality();
            return result;
        }
    }
    async getUserTheme(): Promise<ThemePreference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTheme();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTheme();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listDocuments(): Promise<Array<DocumentMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocuments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocuments();
            return result;
        }
    }
    async listExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpenses();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpenses();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerSpendingMonitorConsent(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSpendingMonitorConsent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSpendingMonitorConsent(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveUserTheme(arg0: ThemePreference): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserTheme(to_candid_ThemePreference_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserTheme(to_candid_ThemePreference_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setAnthropicApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAnthropicApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAnthropicApiKey(arg0);
            return result;
        }
    }
    async setCategoryThreshold(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCategoryThreshold(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCategoryThreshold(arg0, arg1);
            return result;
        }
    }
    async setMonitoredCategories(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMonitoredCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMonitoredCategories(arg0);
            return result;
        }
    }
    async transformHttpResponse(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformHttpResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformHttpResponse(arg0);
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: ExpenseUpdateInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, to_candid_ExpenseUpdateInput_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, to_candid_ExpenseUpdateInput_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadDocument(arg0: DocumentMetaInput): Promise<DocumentMeta> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(arg0);
            return result;
        }
    }
}
function from_candid_AlertStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertStatus): AlertStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_SpendingAlert_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpendingAlert): SpendingAlert {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ThemePreference_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThemePreference): ThemePreference {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentMeta]): DocumentMeta | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ThemePreference]): ThemePreference | null {
    return value.length === 0 ? null : from_candid_ThemePreference_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentMethod: _PaymentMethod;
    source: string;
    date: string;
    note: string;
    createdAt: bigint;
    callerId: Principal;
    updatedAt: [] | [bigint];
    merchant: string;
    category: _ExpenseCategory;
    amount: number;
}): {
    id: bigint;
    paymentMethod: PaymentMethod;
    source: string;
    date: string;
    note: string;
    createdAt: bigint;
    callerId: Principal;
    updatedAt?: bigint;
    merchant: string;
    category: ExpenseCategory;
    amount: number;
} {
    return {
        id: value.id,
        paymentMethod: from_candid_PaymentMethod_n16(_uploadFile, _downloadFile, value.paymentMethod),
        source: value.source,
        date: value.date,
        note: value.note,
        createdAt: value.createdAt,
        callerId: value.callerId,
        updatedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.updatedAt)),
        merchant: value.merchant,
        category: from_candid_ExpenseCategory_n19(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AlertStatus;
    threshold: number;
    spent: number;
    category: string;
}): {
    status: AlertStatus;
    threshold: number;
    spent: number;
    category: string;
} {
    return {
        status: from_candid_AlertStatus_n26(_uploadFile, _downloadFile, value.status),
        threshold: value.threshold,
        spent: value.spent,
        category: value.category
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mode: string;
    palette: string;
    customColor: [] | [string];
}): {
    mode: string;
    palette: string;
    customColor?: string;
} {
    return {
        mode: value.mode,
        palette: value.palette,
        customColor: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.customColor))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    Card: null;
} | {
    Cash: null;
} | {
    Other: null;
} | {
    NetBanking: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "Card" in value ? PaymentMethod.Card : "Cash" in value ? PaymentMethod.Cash : "Other" in value ? PaymentMethod.Other : "NetBanking" in value ? PaymentMethod.NetBanking : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Food: null;
} | {
    Health: null;
} | {
    Bills: null;
} | {
    Travel: null;
} | {
    Entertainment: null;
} | {
    Shopping: null;
} | {
    Other: null;
} | {
    Transport: null;
}): ExpenseCategory {
    return "Food" in value ? ExpenseCategory.Food : "Health" in value ? ExpenseCategory.Health : "Bills" in value ? ExpenseCategory.Bills : "Travel" in value ? ExpenseCategory.Travel : "Entertainment" in value ? ExpenseCategory.Entertainment : "Shopping" in value ? ExpenseCategory.Shopping : "Other" in value ? ExpenseCategory.Other : "Transport" in value ? ExpenseCategory.Transport : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Dismissed: null;
}): AlertStatus {
    return "Active" in value ? AlertStatus.Active : "Dismissed" in value ? AlertStatus.Dismissed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): RiskLevel {
    return "Low" in value ? RiskLevel.Low : "High" in value ? RiskLevel.High : "Medium" in value ? RiskLevel.Medium : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SpendingAlert>): Array<SpendingAlert> {
    return value.map((x)=>from_candid_SpendingAlert_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n14(_uploadFile, _downloadFile, x));
}
function to_candid_ExpenseCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseInput): _ExpenseInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseUpdateInput_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseUpdateInput): _ExpenseUpdateInput {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ThemePreference_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThemePreference): _ThemePreference {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mode: string;
    palette: string;
    customColor?: string;
}): {
    mode: string;
    palette: string;
    customColor: [] | [string];
} {
    return {
        mode: value.mode,
        palette: value.palette,
        customColor: value.customColor ? candid_some(value.customColor) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod?: PaymentMethod;
    date?: string;
    note?: string;
    merchant?: string;
    category?: ExpenseCategory;
    amount?: number;
}): {
    paymentMethod: [] | [_PaymentMethod];
    date: [] | [string];
    note: [] | [string];
    merchant: [] | [string];
    category: [] | [_ExpenseCategory];
    amount: [] | [number];
} {
    return {
        paymentMethod: value.paymentMethod ? candid_some(to_candid_PaymentMethod_n10(_uploadFile, _downloadFile, value.paymentMethod)) : candid_none(),
        date: value.date ? candid_some(value.date) : candid_none(),
        note: value.note ? candid_some(value.note) : candid_none(),
        merchant: value.merchant ? candid_some(value.merchant) : candid_none(),
        category: value.category ? candid_some(to_candid_ExpenseCategory_n12(_uploadFile, _downloadFile, value.category)) : candid_none(),
        amount: value.amount ? candid_some(value.amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    source: string;
    date: string;
    note: string;
    merchant: string;
    category: ExpenseCategory;
    amount: number;
}): {
    paymentMethod: _PaymentMethod;
    source: string;
    date: string;
    note: string;
    merchant: string;
    category: _ExpenseCategory;
    amount: number;
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n10(_uploadFile, _downloadFile, value.paymentMethod),
        source: value.source,
        date: value.date,
        note: value.note,
        merchant: value.merchant,
        category: to_candid_ExpenseCategory_n12(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    Card: null;
} | {
    Cash: null;
} | {
    Other: null;
} | {
    NetBanking: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.Card ? {
        Card: null
    } : value == PaymentMethod.Cash ? {
        Cash: null
    } : value == PaymentMethod.Other ? {
        Other: null
    } : value == PaymentMethod.NetBanking ? {
        NetBanking: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): {
    Food: null;
} | {
    Health: null;
} | {
    Bills: null;
} | {
    Travel: null;
} | {
    Entertainment: null;
} | {
    Shopping: null;
} | {
    Other: null;
} | {
    Transport: null;
} {
    return value == ExpenseCategory.Food ? {
        Food: null
    } : value == ExpenseCategory.Health ? {
        Health: null
    } : value == ExpenseCategory.Bills ? {
        Bills: null
    } : value == ExpenseCategory.Travel ? {
        Travel: null
    } : value == ExpenseCategory.Entertainment ? {
        Entertainment: null
    } : value == ExpenseCategory.Shopping ? {
        Shopping: null
    } : value == ExpenseCategory.Other ? {
        Other: null
    } : value == ExpenseCategory.Transport ? {
        Transport: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
